# -*- ruby -*-

# DO NOT EDIT THIS FILE. Instead, edit Rakefile, and run `rake bundler:gemfile`.

source "https://rubygems.org/"

gem "gli", ">=0"
gem "colorize", ">=0"

gem "hoe-yard", ">=0.1.2", :group => [:development, :test]
gem "hoe-bundler", "~>1.2", :group => [:development, :test]
gem "yard", ">=0", :group => [:development, :test]
gem "redcarpet", ">=0", :group => [:development, :test]
gem "rspec", ">=0", :group => [:development, :test]
gem "cucumber", ">=0", :group => [:development, :test]
gem "ci_reporter", ">=0", :group => [:development, :test]
gem "simplecov-rcov", ">=0", :group => [:development, :test]
gem "hoe", "~>3.11", :group => [:development, :test]

# vim: syntax=ruby
